<%@ Page Title="" Language="C#" MasterPageFile="~/Site/MantainTemplate.master" AutoEventWireup="true" CodeBehind="ListArtist.aspx.cs" Inherits="WebForms.Site.ArtistWeb.ListArtist" %>

<asp:Content ID="ButtonContent" ContentPlaceHolderID="ButtonContent" runat="server">
    <a class="btn btn-info" href="CreateArtist.aspx">
        <span class="glyphicon glyphicon-plus"></span>Crear Artist
    </a>
</asp:Content>
<asp:Content ID="ListContent" ContentPlaceHolderID="ArtistContent" runat="server">
    <div class="row">
        <h3>Artist List</h3>
    </div>
    <asp:SqlDataSource ID="SqlDataSource"
        runat="server"
        ConnectionString="<%$ ConnectionStrings:ChinookConnection %>"
        SelectCommand="GetListOfArtist"
        SelectCommandType="StoredProcedure"
        DeleteCommand="DeleteArtist"
        DeleteCommandType="StoredProcedure">
        <DeleteParameters>
            <asp:Parameter Name="artistId" Type="Int32" />
        </DeleteParameters>
    </asp:SqlDataSource>

    <div class="row">
        <br />
        <asp:GridView ID="artistGridView"
            runat="server"
            AllowPaging="True"
            AllowSorting="True"
            AutoGenerateColumns="True"
            DataSourceID="SqlDataSource"
            AutoGenerateDeleteButton="True"
            AutoGenerateEditButton="True">
        </asp:GridView>
        <br />
    </div>

</asp:Content>
