<%@ Page Title="" Language="C#" MasterPageFile="~/Site/MantainTemplate.master" AutoEventWireup="true" CodeBehind="ListArtist.aspx.cs" Inherits="WebForms.Site.ArtistWeb.ListArtist" %>

<asp:Content ID="ButtonContent" ContentPlaceHolderID="ButtonContent" runat="server">
    <a class="btn btn-info" href="CreateArtist.aspx">
        <span class="glyphicon glyphicon-plus"></span>Crear Artist
    </a>
</asp:Content>
<asp:Content ID="ListContent" ContentPlaceHolderID="ArtistContent" runat="server">
    <div class="row">
        <h3>Artist List</h3>
        <br />
        <asp:UpdatePanel ID="ArtistUpdatePanel" runat="server">
            <ContentTemplate>
                <asp:SqlDataSource ID="SqlDataSource"
                    runat="server"
                    ConnectionString="<%$ ConnectionStrings:ChinookConnection %>"
                    SelectCommand="GetListOfArtist"
                    SelectCommandType="StoredProcedure"
                    DeleteCommand="DeleteArtist"
                    DeleteCommandType="StoredProcedure" UpdateCommand="UpdateArtist" UpdateCommandType="StoredProcedure">
                    <DeleteParameters>
                        <asp:Parameter Name="artistId" Type="Int32" />
                    </DeleteParameters>
                    <UpdateParameters>
                        <asp:Parameter Name="artistId" Type="Int32" />
                        <asp:Parameter Name="name" Type="String" />
                    </UpdateParameters>
                </asp:SqlDataSource>

                <div class="row">
                    <br />
                    <asp:GridView ID="artistGridView"
                        runat="server"
                        AllowPaging="True"
                        AllowSorting="True"
                        AutoGenerateColumns="False"
                        DataSourceID="SqlDataSource"
                        AutoGenerateDeleteButton="True"
                        AutoGenerateEditButton="True" DataKeyNames="ArtistId">
                        <Columns>
                            <asp:BoundField DataField="ArtistId" HeaderText="ArtistId" InsertVisible="False" ReadOnly="True" SortExpression="ArtistId" />
                            <asp:BoundField DataField="Name" HeaderText="Name" SortExpression="Name" />
                        </Columns>
                    </asp:GridView>
                    <br />
                </div>
            </ContentTemplate>
        </asp:UpdatePanel>
    </div>
</asp:Content>
